import { useState } from 'react'
import { fmtNumber } from '../format'
import type { AlertCard, LiqReview, LogEntry, Role } from '../types'

const filters = ['all', 'alert', 'transition', 'decision', 'comm', 'note'] as const

export function IncidentLog({ log, alerts, role, busy, onAck, onNote, onReview }: { log: LogEntry[]; alerts: AlertCard[]; role: Role | 'All'; busy: boolean; onAck: (id: string, actor: Role) => Promise<void>; onNote: (text: string, actor: Role) => Promise<void>; onReview: (verdict: LiqReview, rationale: string) => Promise<void> }) {
  const [filter, setFilter] = useState<(typeof filters)[number]>('all')
  const [note, setNote] = useState('')
  const [review, setReview] = useState<LiqReview>('under-review')
  const [rationale, setRationale] = useState('')
  const [expanded, setExpanded] = useState<number | null>(null)
  const actor: Role = role === 'All' ? 'IC' : role
  const entries = log.filter((entry) => filter === 'all' || entry.type === filter).slice().reverse()
  const activeAlerts = alerts.filter((alert) => !alert.acknowledged_by)
  return <section className="border border-line bg-white p-3 md:p-4" aria-label="Incident log">
    <div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-xs font-bold uppercase tracking-[0.13em]">Incident log</h2><span className="text-[11px] text-muted">{log.length} entries · newest first</span></div>
    {activeAlerts.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{activeAlerts.map((alert) => <button key={alert.id} type="button" disabled={busy} onClick={() => void onAck(alert.id, actor).catch(() => {})} className="border border-amber-300 bg-amber-50 px-2 py-1 text-[11px] text-amber-950 disabled:opacity-50">Acknowledge {alert.signal} · {alert.count}×</button>)}</div>}
    <div className="mt-3 flex flex-wrap gap-1" role="group" aria-label="Filter log entries">{filters.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`border px-2 py-1 text-[10px] capitalize ${filter === item ? 'border-navy bg-navy text-white' : 'border-line text-muted'}`}>{item}</button>)}</div>
    <ol className="mt-3 max-h-80 divide-y divide-line overflow-y-auto border-y border-line">{entries.length ? entries.map((entry) => <li key={entry.id} className="py-2 text-xs"><div className="flex gap-2"><span className="w-14 shrink-0 font-mono text-[11px] text-muted">{entry.t_label}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><span className="font-semibold uppercase text-navy">{entry.type}</span><span className="text-[10px] text-muted">{entry.actor} · SEV-{entry.sev}</span>{entry.liquidation_review && <span className="border border-amber-300 px-1 text-[10px] text-amber-900">Liq: {entry.liquidation_review}</span>}</div><p className="mt-0.5 leading-snug">{entry.action}</p>{entry.rationale && <p className="mt-1 text-[11px] text-muted">Why: {entry.rationale}</p>}{Object.keys(entry.signal_snapshot).length > 0 && <><button type="button" onClick={() => setExpanded((id) => id === entry.id ? null : entry.id)} className="mt-1 text-[11px] text-navy underline">{expanded === entry.id ? 'Hide' : 'Show'} signal snapshot</button>{expanded === entry.id && <p className="mt-1 font-mono text-[10px] text-muted">{Object.entries(entry.signal_snapshot).map(([key, value]) => `${key} ${fmtNumber(value)}`).join(' · ')}</p>}</>}</div></div></li>) : <li className="p-4 text-xs text-muted">No log entries match this filter.</li>}</ol>
    <form className="mt-3 flex gap-2" onSubmit={(e) => { e.preventDefault(); if (note.trim()) void onNote(note.trim(), actor).then(() => setNote('')).catch(() => {}) }}><label htmlFor="incident-note" className="sr-only">Add incident note</label><input id="incident-note" className="min-w-0 flex-1 border border-line px-2 py-1.5 text-xs" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add a decision or observation" /><button type="submit" disabled={busy || !note.trim()} className="border border-navy px-2 py-1 text-xs font-semibold text-navy disabled:opacity-50">Add note</button></form>
    <div className="mt-3 border-t border-line pt-3"><h3 className="text-[11px] font-semibold">Abnormal liquidation review · IC</h3><div className="mt-2 flex flex-wrap gap-2"><select className="border border-line px-2 py-1 text-xs" aria-label="Liquidation review verdict" value={review} onChange={(e) => setReview(e.target.value as LiqReview)} disabled={role !== 'IC'}><option value="under-review">Under review</option><option value="market-explained">Market-explained</option><option value="wrongful">Wrongful</option></select><input className="min-w-44 flex-1 border border-line px-2 py-1 text-xs" aria-label="Liquidation review rationale" placeholder="Evidence and reason" value={rationale} onChange={(e) => setRationale(e.target.value)} disabled={role !== 'IC'} /><button type="button" disabled={busy || role !== 'IC' || !rationale.trim()} onClick={() => void onReview(review, rationale.trim()).then(() => setRationale('')).catch(() => {})} className="bg-navy px-2 py-1 text-xs font-semibold text-white disabled:opacity-50">Record review</button></div>{role !== 'IC' && <p className="mt-1 text-[10px] text-muted">Select IC to record a liquidation verdict.</p>}</div>
  </section>
}

