// H0 stub fixtures, typed. Source of truth is docs/contracts/fixtures/*.json
// (hand-written / generated by docs/contracts/make_fixtures.py, validated
// against the pydantic models by backend/tests/test_contract_fixtures.py).
// Imported directly as JSON modules rather than copied, so there is exactly
// one copy of each fixture on disk (CONTRACTS.md §8: "When the contract
// changes, update the fixtures in the same PR" — a copy step would be a
// second place to forget). This requires `resolveJsonModule` in
// tsconfig.app.json and `server.fs.allow` in vite.config.ts to reach one
// directory above the repo's `frontend/` root; both are set for this.
//
// `VITE_INCIDENT_MOCK=1` is meant to make the frontend's mock mode cycle
// through `SEQUENCE` (H4/H6); H0 only needs the data typed and compiled.

import stateIdle from '../../../docs/contracts/fixtures/state_idle.json'
import stateNormal from '../../../docs/contracts/fixtures/state_normal.json'
import stateWarning from '../../../docs/contracts/fixtures/state_warning.json'
import stateCritical from '../../../docs/contracts/fixtures/state_critical.json'
import stateEmergency from '../../../docs/contracts/fixtures/state_emergency.json'
import stateStabilising from '../../../docs/contracts/fixtures/state_stabilising.json'
import stateResolved from '../../../docs/contracts/fixtures/state_resolved.json'
import summaryC1 from '../../../docs/contracts/fixtures/summary_c1.json'

import type { IncidentStateDTO, IncidentSummary } from './types'

// JSON module imports are typed structurally from the literal file contents
// (e.g. `history` infers as `number[][]`, not the `[number, number][]`
// tuple type; heterogeneous `log[].signal_snapshot` keys infer as a union
// of narrow object shapes rather than `Record<string, number>`). That's a
// TS JSON-import limitation, not a real shape mismatch — the JSON is
// already validated against the identical pydantic models by
// backend/tests/test_contract_fixtures.py — so each fixture goes through
// `unknown` once, same as TS itself suggests for this exact case.
const asState = (v: unknown) => v as IncidentStateDTO

export const FIXTURES = {
  idle: asState(stateIdle),
  normal: asState(stateNormal),
  warning: asState(stateWarning),
  critical: asState(stateCritical),
  emergency: asState(stateEmergency),
  stabilising: asState(stateStabilising),
  resolved: asState(stateResolved),
} satisfies Record<string, IncidentStateDTO>

// The linear click-through sequence used by the demo (mirrors
// backend/incident/api.py's stub _SEQUENCE). `emergency` is a standalone
// variant reachable only via /incident/inject, not part of this sequence.
export const SEQUENCE: (keyof typeof FIXTURES)[] = [
  'idle',
  'normal',
  'warning',
  'critical',
  'stabilising',
  'resolved',
]

export const SUMMARY_C1 = summaryC1 as unknown as IncidentSummary
